version: '3'
networks:
  internal:
    driver: bridge
services:
  web:
    environment:
      PORT: 3000
      # REDIS_URL: "redis://cache:6379"
      # ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
    build: .
    volumes:
      - ".:/heft-tracker-tool"
      - "bundle:/bundle"
    ports: ["3000:3000"]
    networks: [internal]
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
  # cache:
  #   image: redis:5.0.8-alpine
  #   expose: ["6379"]
  #   networks: [internal]
volumes:
  bundle: # see https://dev.to/k_penguin_sato/cache-rails-gems-using-docker-compose-3o3f
